# Generated by Django 6.0.1 on 2026-01-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('user', 'User'), ('shelter', 'Shelter'), ('admin', 'Admin')], default='user', max_length=10)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
