# Generated by Django 5.0.6 on 2026-04-12 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('boarding_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'boarding_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField()),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'order_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=20)),
                ('payment_mode', models.CharField(max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'order_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=6)),
                ('pet_image', models.ImageField(blank=True, upload_to='pets/')),
            ],
            options={
                'db_table': 'pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetHealth',
            fields=[
                ('pet_health_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(blank=True, max_length=30, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('medicine', models.CharField(blank=True, max_length=50, null=True)),
                ('last_vaccination', models.DateField(blank=True, null=True)),
                ('next_vaccination', models.DateField(blank=True, null=True)),
                ('vaccine_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reminder_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'pet_health',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShelterPayment',
            fields=[
                ('shelter_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10)),
                ('payment_date', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shelter_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('user', 'User'), ('shelter', 'Shelter'), ('admin', 'Admin')], default='user', max_length=10)),
            ],
            options={
                'db_table': 'user_happypaws',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product_form',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('age_range', models.CharField(max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_form',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_query', models.TextField()),
                ('ai_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='myadmin.user')),
            ],
            options={
                'db_table': 'chat_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.user')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('shelter_id', models.AutoField(primary_key=True, serialize=False)),
                ('shelter_name', models.CharField(max_length=50)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.BigIntegerField()),
                ('capacity', models.IntegerField()),
                ('available_slot_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.user')),
            ],
            options={
                'db_table': 'shelter',
                'managed': True,
            },
        ),
    ]
