# Generated by Django 6.0.1 on 2026-01-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_happypaws',
        ),
    ]
