# Generated by Django 6.0.1 on 2026-01-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_happypaws',
        ),
    ]
