# Generated by Django 6.0.1 on 2026-01-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_user_delete_user_happypaws'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField()),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
