# Generated by Django 6.0.1 on 2026-01-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('shelter_id', models.AutoField(primary_key=True, serialize=False)),
                ('shelter_name', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.BigIntegerField()),
                ('capacity', models.IntegerField()),
                ('available_slot_count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'shelter',
                'managed': False,
            },
        ),
    ]
