# Generated by Django 6.0.1 on 2026-02-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_product_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_form',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
