# Generated by Django 6.0.1 on 2026-02-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_alter_product_form_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'order_table',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_happypaws',
        ),
    ]
