# Generated by Django 6.0.1 on 2026-02-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_order_table_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=6)),
                ('pet_image', models.ImageField(upload_to='pets/')),
            ],
            options={
                'db_table': 'pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetHealth',
            fields=[
                ('pet_health_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(blank=True, max_length=30, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('medicine', models.CharField(blank=True, max_length=50, null=True)),
                ('last_vaccination', models.DateField(blank=True, null=True)),
                ('next_vaccination', models.DateField(blank=True, null=True)),
                ('vaccine_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reminder_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'pet_health',
                'managed': False,
            },
        ),
    ]
