# Generated by Django 6.0.1 on 2026-02-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_pet_pethealth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelter',
            options={},
        ),
    ]
    