# Generated by Django 6.0.1 on 2026-02-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_alter_shelter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelter',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='location',
        ),
        migrations.AddField(
            model_name='shelter',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
