# Generated by Django 5.0.6 on 2026-03-26 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0015_order_item_shelterpayment_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.user'),
        ),
    ]
